local jump_back = require("easy-action.jump_back")

describe("jump_back", function()
	it("postion", function()
		jump_back:save_position()
		assert(jump_back.win_handle ~= nil)
		assert(jump_back.cursor_pos ~= nil)
		assert(jump_back:cursor_doesnt_move() == true)
		jump_back:clear()
		assert(jump_back.win_handle == nil)
		assert(jump_back.cursor_pos == nil)
		assert(jump_back:cursor_doesnt_move() == false)
	end)
end)
